Name = input("What is your name?")
Age = input("What is your age?")
print("Gee that's REALLY OLD")
replit = input("Do you like Replit?")
print("OF COURSE YOU DO!")
print()
print("So you are")
print(Name)
print("and are ripe old of age")
print(Age)
print("and clearly think that Replit is")
print(replit)

#DAY2 CHALLENGE
#GETTING TO KNOW YOU!
Name = input("What's your name?")
print()
Food = input("What's your favourite food?")
print()
Music = input("What's your favourite music?")
print()
Residence = input("Where do you live?")
print()

print("You are")
print(Name)
print("You're probably hungry for")
print(Food)
print("and you're definitely getting your groove on to")
print(Music)
print("living in the amazing city of")
print(Residence)